///////////////////////////////////////////////////////////////////////////////
// LibInterfaceClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "LibInterfaceClassFactory.h"
#include "LibInterfaceServices.h"
#include "LibInterfaceVersion.h"
#include "LibInterface.h"

BEGIN_CLASS_MAP(CLibInterfaceClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_LibInterfaceCLibInterface, SRVNAME_LIBINTERFACE "!CLibInterface", CLibInterface)
///</AutoGeneratedContent>
END_CLASS_MAP()

CLibInterfaceClassFactory::CLibInterfaceClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_LIBINTERFACE)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(LibInterface));
#endif //defined(TCDBG_UNIT_VERSION)
}

